### ISSUE TITLE
pyfribidi build against fribidi 1.0.8 fails

### ISSUE THREAD

**Issue by aelmahmoudy** [fribidi/fribidi#136]
When building pyfribidi against fribidi 1.0.8, I got the following error:
```
======================================================================
FAIL: testNoReorderNonSpacingMarks (test_pyfribidi.UTF8Tests)
utf8: reorder non spacing marks
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/python-team/modules/pyfribidi/debian/output/pyfribidi-0.12.0+repack/.pybuild/cpython3_3.8/build/test_pyfribidi.py", line 146, in testNoReorderNonSpacingMarks
    self.assertEqual(pyfribidi.log2vis("חַיְפַא", RTL, reordernsm=False),
AssertionError: 'אפַיְחַ' != 'אַפְיַח'
- אפַיְחַ
+ אַפְיַח


======================================================================
FAIL: testNoReorderNonSpacingMarks (test_pyfribidi.UnicodeTests)
unicode: reorder non spacing marks
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/python-team/modules/pyfribidi/debian/output/pyfribidi-0.12.0+repack/.pybuild/cpython3_3.8/build/test_pyfribidi.py", line 90, in testNoReorderNonSpacingMarks
    self.assertEqual(pyfribidi.log2vis(u"חַיְפַא", RTL, reordernsm=False),
AssertionError: 'אפַיְחַ' != 'אַפְיַח'
- אפַיְחַ
+ אַפְיַח
```

I didn't face this issue when building against fribidi 1.0.7

**Comment by dov** [comment]
Do you mind giving the complete steps to reproduce this?

**Comment by aelmahmoudy** [comment]
python3 setup.py build
python3 -m unittest discover -v

Complete build log available on: 
ttps://salsa.debian.org/python-team/modules/pyfribidi/-/jobs/484254/raw

**Comment by dov** [comment]
Ok, thanks. After some tweaking I managed to run the test and got the same error.

@behdad  Do you have any idea? The reordering code hasn't changed. 

Compare with UBA: https://unicode.org/cldr/utility/bidic.jsp?s=%D7%97%D6%B7%D7%99%D6%B0%D7%A4%D6%B7%D7%90&b=1&u=110&d=4

FriBidi returns a different result when `fribidi_set_reorder_nsm(FALSE)`.

**Comment by aelmahmoudy** [comment]
The difference between the two outputs in hex is as follows: 
- d790 d7a4 d6b7 d799 d6b0 d797 d6b7
+ d790 d6b7 d7a4 d6b0 d799 d6b7 d797
