### ISSUE TITLE
Meson build error on Windows

### ISSUE THREAD

**Issue by floppyhammer** [fribidi/fribidi#194]
```
PS D:\Dev\Projects\fribidi> meson setup build
The Meson build system
Version: 1.0.0
Source dir: D:\Dev\Projects\fribidi
Build dir: D:\Dev\Projects\fribidi\build
Build type: native build
Project name: fribidi
Project version: 1.0.12
Activating VS 17.4.4
C compiler for the host machine: cl (msvc 19.34.31937 "Microsoft (R) C/C++ Optimizing Compiler Version 19.34.31937 for x64")
C linker for the host machine: link link 14.34.31937.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Checking for function "memmove" : YES
Checking for function "memset" : YES
Checking for function "strdup" : YES
Has header "stdlib.h" : YES
Has header "string.h" : YES
Has header "memory.h" : YES
Has header "strings.h" : NO
Has header "sys/times.h" : NO
Has header "strings.h" : NO (cached)
Configuring config.h using configuration
Has header "stdlib.h" : YES (cached)
Has header "string.h" : YES (cached)
Has header "strings.h" : NO (cached)
Checking for size of "int" : 4
Configuring fribidi-config.h using configuration
Program test-runner.py found: YES (C:\Program Files\Meson\meson.exe runpython D:\Dev\Projects\fribidi\test\test-runner.py)
doc\meson.build:2: WARNING: Project targets '>= 0.54' but uses feature deprecated since '0.48.0': module python3.
WARNING: You should add the boolean check kwarg to the run_command call.
         It currently defaults to false,
         but it will default to true in future releases of meson.
         See also: https://github.com/mesonbuild/meson/issues/9300

doc\meson.build:9:2: ERROR: Problem encountered: Could not extract list of symbols from fribidi.def.

A full log can be found at D:\Dev\Projects\fribidi\build\meson-logs\meson-log.txt
```

Need a bit of help with this. Thanks in advance.

**Comment by tp-m** [comment]
> A full log can be found at D:\Dev\Projects\fribidi\build\meson-logs\meson-log.txt

Could you attach this file please?

**Comment by floppyhammer** [comment]
@tp-m [meson-log.txt](https://github.com/fribidi/fribidi/files/10417244/meson-log.txt)

**Comment by tp-m** [comment]
```
Running command: C:\Program Files\Meson\meson.exe runpython -c import sys; print(open(sys.argv[1], "r").read()) D:\Dev\Projects\fribidi\doc\../lib/fribidi.def
--- stdout ---

--- stderr ---
Traceback (most recent call last):
  File "mesonbuild\mesonmain.py", line 193, in run
  File "mesonbuild\mesonmain.py", line 144, in run_runpython_command
  File "<string>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'runpython'


doc\meson.build:9:2: ERROR: Problem encountered: Could not extract list of symbols from fribidi.def.
```

Not sure what's happening here. Looks like a Meson issue or something with your python install perhaps?

(On GStreamer's CI we can build fribidi 1.0.12 just fine with Meson 1.0.0 in MSVC fwiw.)

Could try and fix the warning and migrate this over to the new python stuff of course.

**Comment by floppyhammer** [comment]
@tp-m I have no problem running

<img width="424" alt="image" src="https://user-images.githubusercontent.com/28705694/212471684-9dba7d6e-9033-4ec9-b478-29fdb61c765c.png">

So I suppose my python install is good. It may have something to do with `open(sys.argv[1], "r").read()`.

**Comment by eli-schwartz** [comment]
This appears to be a bug in Meson -- Meson will, if no version of Python is found on your system, attempt to "find" python3 by diverting to an internal execution path. This worked fine for running scripts, but not for running `-c 'code to execute'`, because we forgot to shift arguments over the way python itself does.

The fix is here: https://github.com/mesonbuild/meson/pull/11297

**Comment by nirbheek** [comment]
Fixed by https://github.com/mesonbuild/meson/pull/11297
