### ISSUE TITLE
Error compiling with msvc

### ISSUE THREAD

**Issue by nacho** [fribidi/fribidi#74]
Here is the error I get with the last release:

PS C:\gtk-build\gvsbuild> C:\Python36\python.exe .\build.py build -p x64 fribidi
C:\gtk-build\src\fribidi-1.0.2.tar.bz2 - Download finished
Building project ninja
Building project meson
Building project fribidi
The Meson build system
Version: 0.44.0
Source dir: C:\gtk-build\build\x64\release\fribidi
Build dir: C:\gtk-build\build\x64\release\fribidi-meson
Build type: native build
Project name: fribidi
Native C compiler: cl (msvc 18.00.21005.1)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Compiler for C supports argument -fvisibility=hidden: NO
Checking for function "memmove": YES
Checking for function "memset": YES
Checking for function "strdup": YES
Has header "stdlib.h": YES
Has header "string.h": YES
Has header "memory.h": YES
Has header "strings.h": NO
Has header "sys/times.h": NO
Has header "strings.h": NO
Configuring config.h using configuration
Has header "stdlib.h": YES
Has header "string.h": YES
Has header "strings.h": NO
Checking for size of "int": 4
Configuring fribidi-config.h using configuration
Program test-runner.py found: YES (C:\Python36\python.exe C:\gtk-build\build\x64\release\fribidi\test\test-runner.py)

Meson encountered an error in file test\meson.build, line 16, column 2:
File test_CapRTL_isolate.input does not exist.

A full log can be found at C:\gtk-build\build\x64\release\fribidi-meson\meson-logs\meson-log.txt
Traceback (most recent call last):
  File "C:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 325, in build
    self.__build_one(p)
  File "C:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 404, in __build_one
    proj.build()
  File "C:\gtk-build\gvsbuild\gvsbuild\projects.py", line 334, in build
    Meson.build(self)
  File "C:\gtk-build\gvsbuild\gvsbuild\utils\base_builders.py", line 52, in build
    self.exec_vs(cmd)
  File "C:\gtk-build\gvsbuild\gvsbuild\utils\base_project.py", line 71, in exec_vs
    self.builder.exec_vs(cmd, working_dir=self._get_working_dir(), add_path=add_path)
  File "C:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 614, in exec_vs
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "C:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 646, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Python36\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\Python36\python.exe C:\gtk-build\tools\meson-0.44.0\meson.py C:\gtk-build\build\x64\release\fribidi C:\gtk-build\build\x64\release\fribidi-meson --prefix C:\gtk-build\gtk\x64\release --buildtype release' returned non-zero exit status 1.
Error: fribidi build failed

**Comment by nacho** [comment]
After trying to build from master I get the following which I guess it is related with the other issue:

PS C:\gtk-build\gvsbuild> C:\Python36\python.exe .\build.py build -p x64 fribidi
Building project ninja
Building project meson
Building project fribidi
Cloning into 'C:\gtk-build\build\x64\release\fribidi-tmp'...
remote: Counting objects: 2341, done.
remote: Compressing objects: 100% (69/69), done.
Rremote: Total 2341 (delta 57), reused 93 (delta 48), pack-reused 2224
Receiving objects: 100% (2341/2341), 4.28 MiB | 404.00 KiB/s, done.
Resolving deltas: 100% (1746/1746), done.
Already on 'master'
Your branch is up to date with 'origin/master'.
The Meson build system
Version: 0.44.0
Source dir: C:\gtk-build\build\x64\release\fribidi
Build dir: C:\gtk-build\build\x64\release\fribidi-meson
Build type: native build
Project name: fribidi
Native C compiler: cl (msvc 18.00.21005.1)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Compiler for C supports argument -fvisibility=hidden: NO
Checking for function "memmove": YES
Checking for function "memset": YES
Checking for function "strdup": YES
Has header "stdlib.h": YES
Has header "string.h": YES
Has header "memory.h": YES
Has header "strings.h": NO
Has header "sys/times.h": NO
Has header "strings.h": NO
Configuring config.h using configuration
Has header "stdlib.h": YES
Has header "string.h": YES
Has header "strings.h": NO
Checking for size of "int": 4
Configuring fribidi-config.h using configuration
Program test-runner.py found: YES (C:\Python36\python.exe C:\gtk-build\build\x64\release\fribidi\test\test-runner.py)
Program c2man found: NO
Program nonexistingprogram found: NO

Meson encountered an error in file doc\meson.build, line 4, column 2:
Error encountered: c2man is required to build documentation. Or disable with -Ddocs=false

A full log can be found at C:\gtk-build\build\x64\release\fribidi-meson\meson-logs\meson-log.txt
Traceback (most recent call last):
  File "C:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 325, in build
    self.__build_one(p)
  File "C:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 404, in __build_one
    proj.build()
  File "C:\gtk-build\gvsbuild\gvsbuild\projects.py", line 335, in build
    Meson.build(self)
  File "C:\gtk-build\gvsbuild\gvsbuild\utils\base_builders.py", line 52, in build
    self.exec_vs(cmd)
  File "C:\gtk-build\gvsbuild\gvsbuild\utils\base_project.py", line 71, in exec_vs
    self.builder.exec_vs(cmd, working_dir=self._get_working_dir(), add_path=add_path)
  File "C:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 614, in exec_vs
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "C:\gtk-build\gvsbuild\gvsbuild\utils\builder.py", line 646, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Python36\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\Python36\python.exe C:\gtk-build\tools\meson-0.44.0\meson.py C:\gtk-build\build\x64\release\fribidi C:\gtk-build\build\x64\release\fribidi-meson --prefix C:\gtk-build\gtk\x64\release --buildtype release' returned non-zero exit status 1.
Error: fribidi build failed

**Comment by nacho** [comment]
Passing in -Ddocs=false builds like a charm. So I guess the point here is that we need to include all the files in the dist check and make a new release?
